// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/consumer/consumer.proto

package consumer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConsumerRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=SessionToken,proto3" json:"SessionToken,omitempty"`
	URL                  string   `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	RequestBody          []byte   `protobuf:"bytes,3,opt,name=RequestBody,proto3" json:"RequestBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumerRequest) Reset()         { *m = ConsumerRequest{} }
func (m *ConsumerRequest) String() string { return proto.CompactTextString(m) }
func (*ConsumerRequest) ProtoMessage()    {}
func (*ConsumerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e80ff436817566e4, []int{0}
}

func (m *ConsumerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumerRequest.Unmarshal(m, b)
}
func (m *ConsumerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumerRequest.Marshal(b, m, deterministic)
}
func (m *ConsumerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerRequest.Merge(m, src)
}
func (m *ConsumerRequest) XXX_Size() int {
	return xxx_messageInfo_ConsumerRequest.Size(m)
}
func (m *ConsumerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerRequest proto.InternalMessageInfo

func (m *ConsumerRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *ConsumerRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *ConsumerRequest) GetRequestBody() []byte {
	if m != nil {
		return m.RequestBody
	}
	return nil
}

type ConsumerResponse struct {
	StatusCode           int32             `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	StatusMessage        string            `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	Header               map[string]string `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ConsumerResponse) Reset()         { *m = ConsumerResponse{} }
func (m *ConsumerResponse) String() string { return proto.CompactTextString(m) }
func (*ConsumerResponse) ProtoMessage()    {}
func (*ConsumerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e80ff436817566e4, []int{1}
}

func (m *ConsumerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumerResponse.Unmarshal(m, b)
}
func (m *ConsumerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumerResponse.Marshal(b, m, deterministic)
}
func (m *ConsumerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerResponse.Merge(m, src)
}
func (m *ConsumerResponse) XXX_Size() int {
	return xxx_messageInfo_ConsumerResponse.Size(m)
}
func (m *ConsumerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerResponse proto.InternalMessageInfo

func (m *ConsumerResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ConsumerResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *ConsumerResponse) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ConsumerResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*ConsumerRequest)(nil), "ConsumerRequest")
	proto.RegisterType((*ConsumerResponse)(nil), "ConsumerResponse")
	proto.RegisterMapType((map[string]string)(nil), "ConsumerResponse.HeaderEntry")
}

func init() { proto.RegisterFile("proto/consumer/consumer.proto", fileDescriptor_e80ff436817566e4) }

var fileDescriptor_e80ff436817566e4 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0x5d, 0x0a, 0x44, 0xa7, 0x18, 0xcb, 0xc4, 0x43, 0x43, 0x82, 0x69, 0x1a, 0x0f, 0x3d,
	0xd5, 0x04, 0x63, 0x22, 0x1c, 0x25, 0x24, 0x1e, 0xf4, 0xb2, 0xe8, 0x03, 0x14, 0x3b, 0x51, 0x82,
	0xee, 0xd6, 0xce, 0x96, 0xa4, 0x47, 0x5f, 0xd4, 0x67, 0x31, 0x5d, 0x0a, 0x16, 0xbc, 0x79, 0xfb,
	0xe7, 0x9b, 0xd9, 0xfd, 0xff, 0x9d, 0x85, 0x61, 0x96, 0x6b, 0xa3, 0xaf, 0x5e, 0xb4, 0xe2, 0xe2,
	0x83, 0xf2, 0x9d, 0x88, 0x2d, 0x0f, 0x97, 0x70, 0x36, 0xad, 0x89, 0xa4, 0xcf, 0x82, 0xd8, 0x60,
	0x08, 0xbd, 0x39, 0x31, 0x2f, 0xb5, 0x7a, 0xd2, 0x2b, 0x52, 0xbe, 0x08, 0x44, 0x74, 0x22, 0xf7,
	0x18, 0x7a, 0xe0, 0x3c, 0xcb, 0x07, 0xbf, 0x65, 0x5b, 0x95, 0xc4, 0x00, 0xdc, 0xfa, 0x82, 0x3b,
	0x9d, 0x96, 0xbe, 0x13, 0x88, 0xa8, 0x27, 0x9b, 0x28, 0xfc, 0x16, 0xe0, 0xfd, 0x7a, 0x71, 0xa6,
	0x15, 0x13, 0x5e, 0x00, 0xb0, 0x49, 0x4c, 0xc1, 0x53, 0x9d, 0x92, 0xb5, 0xea, 0xc8, 0x06, 0xc1,
	0x4b, 0x38, 0xdd, 0x54, 0x8f, 0xc4, 0x9c, 0xbc, 0x52, 0x6d, 0xb9, 0x0f, 0xf1, 0x06, 0xba, 0x6f,
	0x94, 0xa4, 0x94, 0xfb, 0x4e, 0xe0, 0x44, 0xee, 0x68, 0x18, 0x1f, 0x1a, 0xc5, 0xf7, 0xb6, 0x3f,
	0x53, 0x26, 0x2f, 0x65, 0x3d, 0x8c, 0x08, 0xed, 0x45, 0x15, 0xb6, 0x6d, 0xc3, 0x5a, 0x3d, 0x18,
	0x83, 0xdb, 0x18, 0xad, 0x1e, 0xba, 0xa2, 0xb2, 0xde, 0x41, 0x25, 0xf1, 0x1c, 0x3a, 0xeb, 0xe4,
	0xbd, 0xd8, 0x26, 0xd9, 0x14, 0x93, 0xd6, 0xad, 0x18, 0x7d, 0x09, 0x38, 0xde, 0xfa, 0xe2, 0x18,
	0x3c, 0x59, 0xa8, 0xd9, 0x9a, 0x94, 0xd9, 0x31, 0x2f, 0x3e, 0xd8, 0xf5, 0xa0, 0xff, 0x27, 0x68,
	0x78, 0x84, 0x13, 0xe8, 0xcf, 0x8d, 0xce, 0xfe, 0x73, 0x76, 0xd1, 0xb5, 0xdf, 0x7a, 0xfd, 0x13,
	0x00, 0x00, 0xff, 0xff, 0xda, 0xf9, 0x49, 0xa4, 0xf7, 0x01, 0x00, 0x00,
}
