// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/consumer/consumer.proto

package consumer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Consumer service

type ConsumerService interface {
	RunEventConsumer(ctx context.Context, in *ConsumerRequest, opts ...client.CallOption) (*ConsumerResponse, error)
	StopEventConsumer(ctx context.Context, in *ConsumerRequest, opts ...client.CallOption) (*ConsumerResponse, error)
}

type consumerService struct {
	c    client.Client
	name string
}

func NewConsumerService(name string, c client.Client) ConsumerService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "consumer"
	}
	return &consumerService{
		c:    c,
		name: name,
	}
}

func (c *consumerService) RunEventConsumer(ctx context.Context, in *ConsumerRequest, opts ...client.CallOption) (*ConsumerResponse, error) {
	req := c.c.NewRequest(c.name, "Consumer.RunEventConsumer", in)
	out := new(ConsumerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerService) StopEventConsumer(ctx context.Context, in *ConsumerRequest, opts ...client.CallOption) (*ConsumerResponse, error) {
	req := c.c.NewRequest(c.name, "Consumer.StopEventConsumer", in)
	out := new(ConsumerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Consumer service

type ConsumerHandler interface {
	RunEventConsumer(context.Context, *ConsumerRequest, *ConsumerResponse) error
	StopEventConsumer(context.Context, *ConsumerRequest, *ConsumerResponse) error
}

func RegisterConsumerHandler(s server.Server, hdlr ConsumerHandler, opts ...server.HandlerOption) error {
	type consumer interface {
		RunEventConsumer(ctx context.Context, in *ConsumerRequest, out *ConsumerResponse) error
		StopEventConsumer(ctx context.Context, in *ConsumerRequest, out *ConsumerResponse) error
	}
	type Consumer struct {
		consumer
	}
	h := &consumerHandler{hdlr}
	return s.Handle(s.NewHandler(&Consumer{h}, opts...))
}

type consumerHandler struct {
	ConsumerHandler
}

func (h *consumerHandler) RunEventConsumer(ctx context.Context, in *ConsumerRequest, out *ConsumerResponse) error {
	return h.ConsumerHandler.RunEventConsumer(ctx, in, out)
}

func (h *consumerHandler) StopEventConsumer(ctx context.Context, in *ConsumerRequest, out *ConsumerResponse) error {
	return h.ConsumerHandler.StopEventConsumer(ctx, in, out)
}
