// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/producer/producer.proto

package producer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProducerRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=SessionToken,proto3" json:"SessionToken,omitempty"`
	URL                  string   `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	RequestBody          []byte   `protobuf:"bytes,3,opt,name=RequestBody,proto3" json:"RequestBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProducerRequest) Reset()         { *m = ProducerRequest{} }
func (m *ProducerRequest) String() string { return proto.CompactTextString(m) }
func (*ProducerRequest) ProtoMessage()    {}
func (*ProducerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_462332161c0b5e4f, []int{0}
}

func (m *ProducerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProducerRequest.Unmarshal(m, b)
}
func (m *ProducerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProducerRequest.Marshal(b, m, deterministic)
}
func (m *ProducerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProducerRequest.Merge(m, src)
}
func (m *ProducerRequest) XXX_Size() int {
	return xxx_messageInfo_ProducerRequest.Size(m)
}
func (m *ProducerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProducerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProducerRequest proto.InternalMessageInfo

func (m *ProducerRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *ProducerRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *ProducerRequest) GetRequestBody() []byte {
	if m != nil {
		return m.RequestBody
	}
	return nil
}

type ProducerResponse struct {
	StatusCode           int32             `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	StatusMessage        string            `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	Header               map[string]string `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProducerResponse) Reset()         { *m = ProducerResponse{} }
func (m *ProducerResponse) String() string { return proto.CompactTextString(m) }
func (*ProducerResponse) ProtoMessage()    {}
func (*ProducerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_462332161c0b5e4f, []int{1}
}

func (m *ProducerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProducerResponse.Unmarshal(m, b)
}
func (m *ProducerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProducerResponse.Marshal(b, m, deterministic)
}
func (m *ProducerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProducerResponse.Merge(m, src)
}
func (m *ProducerResponse) XXX_Size() int {
	return xxx_messageInfo_ProducerResponse.Size(m)
}
func (m *ProducerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProducerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProducerResponse proto.InternalMessageInfo

func (m *ProducerResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ProducerResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *ProducerResponse) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ProducerResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*ProducerRequest)(nil), "ProducerRequest")
	proto.RegisterType((*ProducerResponse)(nil), "ProducerResponse")
	proto.RegisterMapType((map[string]string)(nil), "ProducerResponse.HeaderEntry")
}

func init() { proto.RegisterFile("proto/producer/producer.proto", fileDescriptor_462332161c0b5e4f) }

var fileDescriptor_462332161c0b5e4f = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xdd, 0xa6, 0x2d, 0x3a, 0xa9, 0x98, 0x0e, 0x1e, 0x42, 0xa1, 0x12, 0x82, 0x87, 0x9c,
	0x22, 0x54, 0x04, 0xdb, 0xa3, 0x52, 0xf0, 0xa0, 0x20, 0x5b, 0x7d, 0x80, 0xd4, 0x0c, 0x5a, 0x2a,
	0xbb, 0x31, 0xbb, 0x5b, 0xc8, 0xd1, 0x17, 0xf5, 0x59, 0x24, 0xdb, 0x6d, 0x4d, 0xeb, 0xad, 0xb7,
	0x7f, 0xbe, 0x99, 0xdd, 0xff, 0xdf, 0x59, 0x18, 0x16, 0xa5, 0xd4, 0xf2, 0xaa, 0x28, 0x65, 0x6e,
	0xde, 0xa8, 0xdc, 0x8a, 0xd4, 0xf2, 0x78, 0x01, 0x67, 0xcf, 0x8e, 0x70, 0xfa, 0x32, 0xa4, 0x34,
	0xc6, 0xd0, 0x9b, 0x91, 0x52, 0x0b, 0x29, 0x5e, 0xe4, 0x92, 0x44, 0xc8, 0x22, 0x96, 0x9c, 0xf0,
	0x1d, 0x86, 0x01, 0x78, 0xaf, 0xfc, 0x31, 0x6c, 0xd9, 0x56, 0x2d, 0x31, 0x02, 0xdf, 0x5d, 0x70,
	0x27, 0xf3, 0x2a, 0xf4, 0x22, 0x96, 0xf4, 0x78, 0x13, 0xc5, 0x3f, 0x0c, 0x82, 0x3f, 0x2f, 0x55,
	0x48, 0xa1, 0x08, 0x2f, 0x00, 0x94, 0xce, 0xb4, 0x51, 0xf7, 0x32, 0x27, 0x6b, 0xd5, 0xe1, 0x0d,
	0x82, 0x97, 0x70, 0xba, 0xae, 0x9e, 0x48, 0xa9, 0xec, 0x9d, 0x9c, 0xe5, 0x2e, 0xc4, 0x1b, 0xe8,
	0x7e, 0x50, 0x96, 0x53, 0x19, 0x7a, 0x91, 0x97, 0xf8, 0xa3, 0x61, 0xba, 0x6f, 0x94, 0x3e, 0xd8,
	0xfe, 0x54, 0xe8, 0xb2, 0xe2, 0x6e, 0x18, 0x11, 0xda, 0xf3, 0x3a, 0x6c, 0xdb, 0x86, 0xb5, 0x7a,
	0x30, 0x06, 0xbf, 0x31, 0x5a, 0x3f, 0x74, 0x49, 0x95, 0xdb, 0x41, 0x2d, 0xf1, 0x1c, 0x3a, 0xab,
	0xec, 0xd3, 0x6c, 0x92, 0xac, 0x8b, 0x49, 0xeb, 0x96, 0x8d, 0xbe, 0x19, 0x1c, 0x6f, 0x7c, 0x71,
	0x0c, 0x01, 0x37, 0x62, 0xba, 0x22, 0xa1, 0xb7, 0x2c, 0x48, 0xf7, 0x76, 0x3d, 0xe8, 0xff, 0x0b,
	0x1a, 0x1f, 0xe1, 0x04, 0xfa, 0x33, 0x2d, 0x8b, 0x43, 0xce, 0xce, 0xbb, 0xf6, 0x5b, 0xaf, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x46, 0xe2, 0xa1, 0xf7, 0x01, 0x00, 0x00,
}
