// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/producer/producer.proto

package producer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Producer service

type ProducerService interface {
	RunEventProducer(ctx context.Context, in *ProducerRequest, opts ...client.CallOption) (*ProducerResponse, error)
	StopEventProducer(ctx context.Context, in *ProducerRequest, opts ...client.CallOption) (*ProducerResponse, error)
}

type producerService struct {
	c    client.Client
	name string
}

func NewProducerService(name string, c client.Client) ProducerService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "producer"
	}
	return &producerService{
		c:    c,
		name: name,
	}
}

func (c *producerService) RunEventProducer(ctx context.Context, in *ProducerRequest, opts ...client.CallOption) (*ProducerResponse, error) {
	req := c.c.NewRequest(c.name, "Producer.RunEventProducer", in)
	out := new(ProducerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerService) StopEventProducer(ctx context.Context, in *ProducerRequest, opts ...client.CallOption) (*ProducerResponse, error) {
	req := c.c.NewRequest(c.name, "Producer.StopEventProducer", in)
	out := new(ProducerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Producer service

type ProducerHandler interface {
	RunEventProducer(context.Context, *ProducerRequest, *ProducerResponse) error
	StopEventProducer(context.Context, *ProducerRequest, *ProducerResponse) error
}

func RegisterProducerHandler(s server.Server, hdlr ProducerHandler, opts ...server.HandlerOption) error {
	type producer interface {
		RunEventProducer(ctx context.Context, in *ProducerRequest, out *ProducerResponse) error
		StopEventProducer(ctx context.Context, in *ProducerRequest, out *ProducerResponse) error
	}
	type Producer struct {
		producer
	}
	h := &producerHandler{hdlr}
	return s.Handle(s.NewHandler(&Producer{h}, opts...))
}

type producerHandler struct {
	ProducerHandler
}

func (h *producerHandler) RunEventProducer(ctx context.Context, in *ProducerRequest, out *ProducerResponse) error {
	return h.ProducerHandler.RunEventProducer(ctx, in, out)
}

func (h *producerHandler) StopEventProducer(ctx context.Context, in *ProducerRequest, out *ProducerResponse) error {
	return h.ProducerHandler.StopEventProducer(ctx, in, out)
}
